server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/Hotel_Service_1
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

spring.application.name=HOTEL-SERVICE

#spring.config.import=configserver:http://localhost:8095
eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true




